var movies = ['<a class="link" href="http://www.imdb.com/title/tt2850386">The Croods 2</a>',
 '<a class="link" href="http://www.imdb.com/title/tt5580536">Southern Fury</a>',
 '<a class="link" href="http://www.imdb.com/title/tt5462326">Mom and Dad</a>',
 '<a class="link" href="http://www.imdb.com/title/tt5460530">Vengeance: A Love Story</a>',
 '<a class="link" href="http://www.imdb.com/title/tt4382824">Army of One</a>',
 '<a class="link" href="http://www.imdb.com/title/tt2032572">USS Indianapolis: Men of Courage</a>',
 '<a class="link" href="http://www.imdb.com/title/tt3774114">Snowden</a>',
 '<a class="link" href="http://www.imdb.com/title/tt4054654">Dog Eat Dog</a>',
 '<a class="link" href="http://www.imdb.com/title/tt3733774">The Trust</a>',
 '<a class="link" href="http://www.imdb.com/title/tt3733778">Pay the Ghost</a>',
 '<a class="link" href="http://www.imdb.com/title/tt3687398">The Runner</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1274586">Dying of the Light</a>',
 '<a class="link" href="http://www.imdb.com/title/tt2467046">Left Behind</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1552224">Outcast</a>',
 '<a class="link" href="http://www.imdb.com/title/tt2401807">Rage</a>',
 '<a class="link" href="http://www.imdb.com/title/tt2382396">Joe</a>',
 '<a class="link" href="http://www.imdb.com/title/tt2005374">The Frozen Ground</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0481499">The Croods</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1656186">Stolen</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1071875">Ghost Rider: Spirit of Vengeance</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1674784">Trespass</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1214962">Seeking Justice</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1502404">Drive Angry</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0479997">Season of the Witch</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0963966">The Sorcerers Apprentice</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1250777">Kick-Ass</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0375568">Astro Boy</a>',
 '<a class="link" href="http://www.imdb.com/title/tt1095217">Bad Lieutenant: Port of Call New Orleans</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0436339">G-Force</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0448011">Knowing</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0814022">Bangkok Dangerous</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0465234">National Treasure: Book of Secrets</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0435705">Next</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0259324">Ghost Rider</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0450345">The Wicker Man</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0469641">World Trade Center</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0429589">The Ant Bully</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0384680">The Weather Man</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0399295">Lord of War</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0368891">National Treasure</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0325805">Matchstick Men</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0268126">Adaptation.</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0305973">Sonny</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0245562">Windtalkers</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0259929">Christmas Carol: The Movie</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0238112">Captain Corellis Mandolin</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0218967">The Family Man</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0187078">Gone in Sixty Seconds</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0163988">Bringing Out the Dead</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0134273">8MM</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0120832">Snake Eyes</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0120632">City of Angels</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0119094">Face/Off</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0118880">Con Air</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0117500">The Rock</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0113627">Leaving Las Vegas</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0113552">Kiss of Death</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0111477">Trapped in Paradise</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0110167">It Could Happen to You</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0109951">Guarding Tess</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0106684">Deadfall</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0105226">Red Rock West</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0106266">Amos & Andrew</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0104438">Honeymoon in Vegas</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0101004">Zandalee</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0099575">Fire Birds</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0100935">Wild at Heart</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0100762/">Time to Kill</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0098577">Vampires Kiss</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0093565">Moonstruck</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0093822">Raising Arizona</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0091738">Peggy Sue Got Married</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0090769">The Boy in Blue</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0086969">Birdy</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0087089">The Cotton Club</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0087968">Racing with the Moon</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0086216">Rumble Fish</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0086525">Valley Girl</a>',
 '<a class="link" href="http://www.imdb.com/title/tt0083929">Fast Times at Ridgemont High</a>'].reverse(); // Reverse list to match date list
